// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPd1SRCDZSi8I8vDl-t5CIrUOTVBvbVM',
    appId: '1:431747585555:web:e2213e6231feecf2f9d1e6',
    messagingSenderId: '431747585555',
    projectId: 'seeme-689a1',
    authDomain: 'seeme-689a1.firebaseapp.com',
    databaseURL: 'https://seeme-689a1-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-689a1.appspot.com',
    measurementId: 'G-0DR1FT63VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2JsphEm0gTJAsQOFHDoe-S1XlC0UmQRg',
    appId: '1:431747585555:android:00087a8b9083ccbaf9d1e6',
    messagingSenderId: '431747585555',
    projectId: 'seeme-689a1',
    databaseURL: 'https://seeme-689a1-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-689a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVWoXKCgL9DbJ6sHbDCQ73h7mgfOB7sM',
    appId: '1:431747585555:ios:072d8772277bf52cf9d1e6',
    messagingSenderId: '431747585555',
    projectId: 'seeme-689a1',
    databaseURL: 'https://seeme-689a1-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-689a1.appspot.com',
    iosClientId: '431747585555-ik4177580hktlt43fmsqmn6o7cbm3pq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.seeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvVWoXKCgL9DbJ6sHbDCQ73h7mgfOB7sM',
    appId: '1:431747585555:ios:072d8772277bf52cf9d1e6',
    messagingSenderId: '431747585555',
    projectId: 'seeme-689a1',
    databaseURL: 'https://seeme-689a1-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-689a1.appspot.com',
    iosClientId: '431747585555-ik4177580hktlt43fmsqmn6o7cbm3pq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.seeme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxPd1SRCDZSi8I8vDl-t5CIrUOTVBvbVM',
    appId: '1:431747585555:web:681342c46333cc42f9d1e6',
    messagingSenderId: '431747585555',
    projectId: 'seeme-689a1',
    authDomain: 'seeme-689a1.firebaseapp.com',
    databaseURL: 'https://seeme-689a1-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-689a1.appspot.com',
    measurementId: 'G-TCVT5NM9PB',
  );

}