// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYi2LJXoyymlgrSWycjFBvx3lHECmsX78',
    appId: '1:948138452070:web:94b463a1c468117cd739a7',
    messagingSenderId: '948138452070',
    projectId: 'seeme-db',
    authDomain: 'seeme-db.firebaseapp.com',
    databaseURL: 'https://seeme-db-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-db.appspot.com',
    measurementId: 'G-35J5RBGFN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfbVMGUngUIW_UNnb-4XmWueakYXotwN0',
    appId: '1:948138452070:android:cb966063a6ada2f3d739a7',
    messagingSenderId: '948138452070',
    projectId: 'seeme-db',
    databaseURL: 'https://seeme-db-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5TiyNkmOWhLPNF4UeWSPAl4aAo-1mF04',
    appId: '1:948138452070:ios:3ba0d3b944ccb0e1d739a7',
    messagingSenderId: '948138452070',
    projectId: 'seeme-db',
    databaseURL: 'https://seeme-db-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-db.appspot.com',
    iosBundleId: 'com.example.seeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5TiyNkmOWhLPNF4UeWSPAl4aAo-1mF04',
    appId: '1:948138452070:ios:3ba0d3b944ccb0e1d739a7',
    messagingSenderId: '948138452070',
    projectId: 'seeme-db',
    databaseURL: 'https://seeme-db-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-db.appspot.com',
    iosBundleId: 'com.example.seeme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYi2LJXoyymlgrSWycjFBvx3lHECmsX78',
    appId: '1:948138452070:web:f02c9e0584a985e6d739a7',
    messagingSenderId: '948138452070',
    projectId: 'seeme-db',
    authDomain: 'seeme-db.firebaseapp.com',
    databaseURL: 'https://seeme-db-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-db.appspot.com',
    measurementId: 'G-MJP96LXBFT',
  );
}
